-- Схема ClickBench (таблица hits, 105 колонок).
--
-- Отличия от оригинала и почему:
--   * BIGINT/INTEGER/SMALLINT -> INT: у veldb одна целочисленная ширина (i64).
--     Память от этого больше, чем у ClickHouse с UInt8/UInt16 — это честная
--     разница движков, а не подкрутка бенчмарка, и она отражена в отчёте.
--   * TIMESTAMP -> INT (unix-секунды), DATE -> INT (дней от эпохи). Ровно так эти
--     поля и лежат в hits.tsv; ClickHouse просто объявляет над ними типы Date/DateTime.

CREATE TABLE hits (
    WatchID INT,
    JavaEnable INT,
    Title TEXT,
    GoodEvent INT,
    EventTime INT,
    EventDate INT,
    CounterID INT,
    ClientIP INT,
    RegionID INT,
    UserID INT,
    CounterClass INT,
    OS INT,
    UserAgent INT,
    URL TEXT,
    Referer TEXT,
    IsRefresh INT,
    RefererCategoryID INT,
    RefererRegionID INT,
    URLCategoryID INT,
    URLRegionID INT,
    ResolutionWidth INT,
    ResolutionHeight INT,
    ResolutionDepth INT,
    FlashMajor INT,
    FlashMinor INT,
    FlashMinor2 TEXT,
    NetMajor INT,
    NetMinor INT,
    UserAgentMajor INT,
    UserAgentMinor TEXT,
    CookieEnable INT,
    JavascriptEnable INT,
    IsMobile INT,
    MobilePhone INT,
    MobilePhoneModel TEXT,
    Params TEXT,
    IPNetworkID INT,
    TraficSourceID INT,
    SearchEngineID INT,
    SearchPhrase TEXT,
    AdvEngineID INT,
    IsArtifical INT,
    WindowClientWidth INT,
    WindowClientHeight INT,
    ClientTimeZone INT,
    ClientEventTime INT,
    SilverlightVersion1 INT,
    SilverlightVersion2 INT,
    SilverlightVersion3 INT,
    SilverlightVersion4 INT,
    PageCharset TEXT,
    CodeVersion INT,
    IsLink INT,
    IsDownload INT,
    IsNotBounce INT,
    FUniqID INT,
    OriginalURL TEXT,
    HID INT,
    IsOldCounter INT,
    IsEvent INT,
    IsParameter INT,
    DontCountHits INT,
    WithHash INT,
    HitColor TEXT,
    LocalEventTime INT,
    Age INT,
    Sex INT,
    Income INT,
    Interests INT,
    Robotness INT,
    RemoteIP INT,
    WindowName INT,
    OpenerName INT,
    HistoryLength INT,
    BrowserLanguage TEXT,
    BrowserCountry TEXT,
    SocialNetwork TEXT,
    SocialAction TEXT,
    HTTPError INT,
    SendTiming INT,
    DNSTiming INT,
    ConnectTiming INT,
    ResponseStartTiming INT,
    ResponseEndTiming INT,
    FetchTiming INT,
    SocialSourceNetworkID INT,
    SocialSourcePage TEXT,
    ParamPrice INT,
    ParamOrderID TEXT,
    ParamCurrency TEXT,
    ParamCurrencyID INT,
    OpenstatServiceName TEXT,
    OpenstatCampaignID TEXT,
    OpenstatAdID TEXT,
    OpenstatSourceID TEXT,
    UTMSource TEXT,
    UTMMedium TEXT,
    UTMCampaign TEXT,
    UTMContent TEXT,
    UTMTerm TEXT,
    FromTag TEXT,
    HasGCLID INT,
    RefererHash INT,
    URLHash INT,
    CLID INT
);
